name: post_tracking
description: An application to track postal goods

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.0+1
  drift: ^2.12.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  html: ^0.15.4
  intl: any
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.17



dev_dependencies:
  drift_dev: ^2.12.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - fonts/
    - test_html/
  fonts:
    - family: IRANSansFaNum
      fonts:
        - asset: fonts/IRANSansMobileFaNum.ttf
          weight: 400
        - asset: fonts/IRANSansMobileFaNum-Bold.ttf
          weight: 700
        - asset: fonts/IRANSansMobileFaNum-Light.ttf
          weight: 300
        - asset: fonts/IRANSansMobileFaNum-Medium.ttf
          weight: 500
        - asset: fonts/IRANSansMobileFaNum-UltraLight.ttf
          weight: 200


# flutter pub run flutter_launcher_icons main
flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "dev_assets/post.png"
    background_color: "#6ABF64"
    theme_color: "#6ABF64"
  image_path: "dev_assets/post.png"
  adaptive_icon_foreground: "dev_assets/post_adaptive.png"
  adaptive_icon_background: "#6ABF64"